// Generates apps/edge/src/generated/profile.ts from workbench.profile.json (or the example profile).
// The Worker has no filesystem, so the profile is compiled in. Never hand-edit the output.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const local = join(root, "workbench.profile.json");
const source = existsSync(local) ? local : join(root, "profiles/example.profile.json");
const profile = JSON.parse(readFileSync(source, "utf8"));
const out = join(root, "apps/edge/src/generated/profile.ts");
const body = `// GENERATED by scripts/build-profile.mjs from ${existsSync(local) ? "workbench.profile.json" : "profiles/example.profile.json"}. Do not edit.
import { InstanceProfileSchema } from "../../../../packages/contracts/src/profile.ts";

export const INSTANCE_PROFILE = InstanceProfileSchema.parse(${JSON.stringify(profile, null, 2)});
`;
if (process.argv.includes("--check")) {
  if (!existsSync(out) || readFileSync(out, "utf8") !== body) {
    console.error("apps/edge/src/generated/profile.ts is stale; run pnpm profile:build");
    process.exit(1);
  }
  console.log("Generated profile is current.");
} else {
  writeFileSync(out, body);
  console.log(`Wrote ${out} from ${source}`);
}
