// Compiles the instance profile into packages/contracts/src/generated/instance.ts.
//
// The Worker has no filesystem and the dataset's tool schemas are built at import time, so the
// profile, its industry pack (with any personalization) and the resolved brand names are compiled
// in. Source, in order: --profile <path> or $WORKBENCH_PROFILE, workbench.profile.json, then
// profiles/example.profile.json. The tests use profiles/demo-composite.profile.json.
// Personalization (data/instance-dataset.json) applies only to workbench.profile.json.
// Never hand-edit the output; rerun `pnpm profile:build`.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { buildInstance } from "./lib/instance.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const localProfile = join(root, "workbench.profile.json");
const flag = process.argv.indexOf("--profile");
const requested = flag > -1 ? process.argv[flag + 1] : process.env.WORKBENCH_PROFILE;
const source = requested
  ? join(root, requested)
  : existsSync(localProfile)
    ? localProfile
    : join(root, "profiles/example.profile.json");
const out = join(root, "packages/contracts/src/generated/instance.ts");

const personalizationPath = join(root, "data/instance-dataset.json");
const usePersonalization = source === localProfile && existsSync(personalizationPath);
const instance = buildInstance(
  JSON.parse(readFileSync(source, "utf8")),
  usePersonalization ? JSON.parse(readFileSync(personalizationPath, "utf8")) : undefined,
);
const body = `// GENERATED by scripts/build-profile.mjs from ${relative(root, source)}${usePersonalization ? " + data/instance-dataset.json" : ""}. Do not edit.
import { PackSchema } from "../pack.ts";
import { InstanceProfileSchema } from "../profile.ts";

export const INSTANCE_PROFILE = InstanceProfileSchema.parse(${JSON.stringify(instance.profile, null, 2)});

/** The industry pack with this instance's personalization applied. */
export const INSTANCE_PACK = PackSchema.parse(${JSON.stringify(instance.pack, null, 2)});

/** Display names for the parent brand and the two vertical modules. */
export const INSTANCE_BRANDS = ${JSON.stringify(instance.brands, null, 2)} as const;
`;
if (process.argv.includes("--check")) {
  if (!existsSync(out) || readFileSync(out, "utf8") !== body) {
    console.error("The generated instance is stale; run pnpm profile:build");
    process.exit(1);
  }
  console.log("Generated instance is current.");
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, body);
  console.log(`Wrote ${relative(root, out)} from ${relative(root, source)}`);
}
